#Generated Form Function
function GenerateForm {
########################################################################
# Generated On: 12/17/2014 11:20 PM
# Generated By: Arun
########################################################################

$ErrorActionPreference= 'silentlycontinue'
cls
#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$button4 = New-Object System.Windows.Forms.Button
$richTextBox1 = New-Object System.Windows.Forms.RichTextBox
$statusBar1 = New-Object System.Windows.Forms.StatusBar
$button3 = New-Object System.Windows.Forms.Button
$button2 = New-Object System.Windows.Forms.Button
$button1 = New-Object System.Windows.Forms.Button
$button11 = New-Object System.Windows.Forms.Button
$richTextBox2 = New-Object System.Windows.Forms.RichTextBox

$form1 = New-Object System.Windows.Forms.Form
$button9 = New-Object System.Windows.Forms.Button
$button8 = New-Object System.Windows.Forms.Button
$label9 = New-Object System.Windows.Forms.Label
$textBox9 = New-Object System.Windows.Forms.TextBox
$label10 = New-Object System.Windows.Forms.Label
$label11 = New-Object System.Windows.Forms.Label
$label12 = New-Object System.Windows.Forms.Label
$label13 = New-Object System.Windows.Forms.Label
$label14 = New-Object System.Windows.Forms.Label
$label15 = New-Object System.Windows.Forms.Label
$label16 = New-Object System.Windows.Forms.Label
$label17 = New-Object System.Windows.Forms.Label

$checkBox8 = New-Object System.Windows.Forms.CheckBox
$checkBox7 = New-Object System.Windows.Forms.CheckBox
$checkBox6 = New-Object System.Windows.Forms.CheckBox
$checkBox5 = New-Object System.Windows.Forms.CheckBox
$checkBox4 = New-Object System.Windows.Forms.CheckBox
$checkBox3 = New-Object System.Windows.Forms.CheckBox
$checkBox2 = New-Object System.Windows.Forms.CheckBox
$checkBox1 = New-Object System.Windows.Forms.CheckBox
$label8 = New-Object System.Windows.Forms.Label

$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState

#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_label1_Click= 
{

}

$button11_OnClick= 
{
 $statusBar1.Text="Clearing Data in form2"
$srvv = ""
$textBox9.text = ""
$label10.Text = ""
$label11.Text = ""
$label12.Text = ""
$label13.Text = ""
$label14.Text = ""
$label15.Text = ""
$label16.Text = ""
$label17.Text = ""
$checkbox1.Checked = $false
$checkbox2.Checked = $false
$checkbox3.Checked = $false
$checkbox4.Checked = $false
$checkbox5.Checked = $false
$checkbox6.Checked = $false
$checkbox7.Checked = $false
$checkbox8.Checked = $false

}


$button9_OnClick= 
{
 $statusBar1.Text="checking sessions for logoff"
If(!($textBox9.text ))
{
$statusBar1.Text="Enter Server name.."
}
else
{
$srvv = $textBox9.text
 if ($checkBox1.Checked)
 { 
 $lfid = $label10.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
 if ($checkBox2.Checked)
 { 
 $lfid = $label11.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv" 
 }
 if ($checkBox3.Checked)
 { 
 $lfid = $label12.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
 if ($checkBox4.Checked)
 { 
 $lfid = $label13.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
 if ($checkBox5.Checked)
 { 
 $lfid = $label14.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
  if ($checkBox6.Checked)
 { 
 $lfid = $label15.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
  if ($checkBox7.Checked)
 { 
 $lfid = $label16.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }
  if ($checkBox8.Checked)
 { 
 $lfid = $label17.Text -split("-")
 $lfid1 = $lfid[1]
 $lfnm = $lfid[0]
 logoff $lfid1 /SERVER:$srvv 
 Write-Log -Message "$lfnm session disconnected from Server $srvv"
 $statusBar1.Text="$lfnm session disconnected from Server $srvv"
 }

}
}

$button8_OnClick= 
{
 $statusBar1.Text="collecting session information"
If(!($textBox9.text ))
{
$statusBar1.Text="Enter Server name.."
}
else
{
$srvv = $textBox9.text
$label10.Text = ""
$label11.Text = ""
$label12.Text = ""
$label13.Text = ""
$label14.Text = ""
$label15.Text = ""
$label16.Text = ""
$label17.Text = ""
$checkbox1.Checked = $false
$checkbox2.Checked = $false
$checkbox3.Checked = $false
$checkbox4.Checked = $false
$checkbox5.Checked = $false
$checkbox6.Checked = $false
$checkbox7.Checked = $false
$checkbox8.Checked = $false

$LogFile = "$env:userprofile\Desktop\DesconnectSelected-sessions_" + $([DateTime]::Now.ToString('yyyyMMdd')) + ".log"
 
function Write-Log([string]$message)
{
   Out-File -InputObject $message -FilePath $LogFile -Append
}
 
function Get-Sessions
{
if(!(test-connection $srvv -count 2))
{
Write-Log "ERROR: Server $srvv is NOT reachable"
Write-host "ERROR: Server $srvv is NOT reachable"
$statusBar1.Text="ERROR: Server $srvv is NOT reachable"
}
elseif(test-connection $srvv -count 2)
{
   $queryResults = query session /SERVER:$srvv
   Write-Log -Message "============================="
   Write-Log -Message "$srvv"
   Write-Log -Message "============================="
   $statusBar1.Text="Server $srvv is reachable, collecting sessions"
   $starters = New-Object psobject -Property @{"SessionName" = 0; "UserName" = 0; "ID" = 0; "State" = 0; "Type" = 0; "Device" = 0;}
   foreach ($result in $queryResults)
   {
      try
      {
         if($result.trim().substring(0, $result.trim().indexof(" ")) -eq "SESSIONNAME")
         {
            $starters.UserName = $result.indexof("USERNAME");
            $starters.ID = $result.indexof("ID");
            $starters.State = $result.indexof("STATE");
            $starters.Type = $result.indexof("TYPE");
            $starters.Device = $result.indexof("DEVICE");
            continue;
         }
 
         New-Object psobject -Property @{
            "SessionName" = $result.trim().substring(0, $result.trim().indexof(" ")).trim(">");
            "Username" = $result.Substring($starters.Username, $result.IndexOf(" ", $starters.Username) - $starters.Username);
            "ID" = $result.Substring($result.IndexOf(" ", $starters.Username), $starters.ID - $result.IndexOf(" ", $starters.Username) + 2).trim();
            "State" = $result.Substring($starters.State, $result.IndexOf(" ", $starters.State)-$starters.State).trim();
            "Type" = $result.Substring($starters.Type, $starters.Device - $starters.Type).trim();
            "Device" = $result.Substring($starters.Device).trim()
         }
      } 
      catch 
      {
         $e = $_;
         Write-Log "ERROR: on $srvv" + $e.PSMessageDetails
      }
   }
}
}


$GetallSessions = Get-Sessions | ? {$_.UserName -ne ""} | Select ID, UserName
$sessioncount = 0
foreach ($session in $GetallSessions)
{
$usernm1 = $session.Username
$usernmid = $session.id
$usernm = $usernm1 + "-"+$usernmid
Write-Log -Message $usernm1
write-host "$usernm1"
  
if($sessioncount -eq 0)
{
$label10.Text = $usernm
}
elseif($sessioncount -eq 1)
{
$label11.Text = $usernm
}
elseif($sessioncount -eq 2)
{
$label12.Text = $usernm
}
elseif($sessioncount -eq 3)
{
$label13.Text = $usernm
}
elseif($sessioncount -eq 4)
{
$label14.Text = $usernm
}
elseif($sessioncount -eq 5)
{
$label15.Text = $usernm
}
elseif($sessioncount -eq 6)
{
$label16.Text = $usernm
}
elseif($sessioncount -eq 7)
{
$label17.Text = $usernm
}
elseif($sessioncount -eq 8)
{
$label18.Text = $usernm
}


$sessioncount=$sessioncount+1
   $sessionnames += $usernm
   
   $statusBar1.Text="$usernm  on Server $srvv"
   
}


$statusBar1.Text="done -  Server $srvv"
write-host "done -  Server $srvv"
}
}


$button3_OnClick= 
{
 $statusBar1.Text="Clearing Data in form1"
$richTextBox1.Text = ""
$richTextBox2.lines = ""
}

$button1_OnClick= 
{
 $statusBar1.Text="collecting session data"
If(!($richTextBox1.lines ))
{
$statusBar1.Text="Enter Server name.."
}
else
{
$servers = $richTextBox1.lines

$LogFile = "$env:userprofile\Desktop\Desconnectsessions_" + $([DateTime]::Now.ToString('yyyyMMdd')) + ".log"
 
function Write-Log([string]$message)
{
   Out-File -InputObject $message -FilePath $LogFile -Append
}
 
function Get-Sessions
{
if(!(test-connection $srv -count 2))
{
Write-Log "ERROR: Server $srv is NOT reachable"
Write-host "ERROR: Server $srv is NOT reachable"
$statusBar1.Text="ERROR: Server $srv is NOT reachable"
}
elseif(test-connection $srv -count 2)
{
   $queryResults = query session /SERVER:$srv
   $statusBar1.Text="Server $srv is reachable, collecting sessions"
   $starters = New-Object psobject -Property @{"SessionName" = 0; "UserName" = 0; "ID" = 0; "State" = 0; "Type" = 0; "Device" = 0;}
   foreach ($result in $queryResults)
   {
      try
      {
         if($result.trim().substring(0, $result.trim().indexof(" ")) -eq "SESSIONNAME")
         {
            $starters.UserName = $result.indexof("USERNAME");
            $starters.ID = $result.indexof("ID");
            $starters.State = $result.indexof("STATE");
            $starters.Type = $result.indexof("TYPE");
            $starters.Device = $result.indexof("DEVICE");
            continue;
         }
 
         New-Object psobject -Property @{
            "SessionName" = $result.trim().substring(0, $result.trim().indexof(" ")).trim(">");
            "Username" = $result.Substring($starters.Username, $result.IndexOf(" ", $starters.Username) - $starters.Username);
            "ID" = $result.Substring($result.IndexOf(" ", $starters.Username), $starters.ID - $result.IndexOf(" ", $starters.Username) + 2).trim();
            "State" = $result.Substring($starters.State, $result.IndexOf(" ", $starters.State)-$starters.State).trim();
            "Type" = $result.Substring($starters.Type, $starters.Device - $starters.Type).trim();
            "Device" = $result.Substring($starters.Device).trim()
         }
      } 
      catch 
      {
         $e = $_;
         Write-Log "ERROR: on $srv" + $e.PSMessageDetails
      }
   }
}
}

#mail code
 
foreach($srv in $servers)
{ 
[string]$IncludeStates = '^(Disc)$'
Write-Log -Message "Sessions CleanUp on Server $srv"
Write-Log -Message "============================="
$DisconnectedSessions = Get-Sessions | ? {$_.UserName -ne ""} | Select ID, UserName
foreach ($session in $DisconnectedSessions)
{
   logoff $session.ID /SERVER:$srv
   Write-Log -Message $session.Username 
   $statusBar1.Text="Disconnecting $session.Username  from Server $srv"
}
Write-Log -Message "============================="
Write-Log -Message " "

}
}
$statusBar1.Text="Disconnected all sessions"
Write-Host "=========================================="
Write-host "Disconnected sessions from ALL SERVERS"
Write-Host "=========================================="

}

$button2_OnClick= 
{
$richTextBox2.lines = ""
function Get-Sessions
{

   $queryResults = query session /SERVER:$srv
   $statusBar1.Text="Server $srv is reachable, collecting sessions"
   $starters = New-Object psobject -Property @{"SessionName" = 0; "UserName" = 0; "ID" = 0; "State" = 0; "Type" = 0; "Device" = 0;}
   foreach ($result in $queryResults)
   {
      try
      {
         if($result.trim().substring(0, $result.trim().indexof(" ")) -eq "SESSIONNAME")
         {
            $starters.UserName = $result.indexof("USERNAME");
            $starters.ID = $result.indexof("ID");
            $starters.State = $result.indexof("STATE");
            $starters.Type = $result.indexof("TYPE");
            $starters.Device = $result.indexof("DEVICE");
            continue;
         }
 
         New-Object psobject -Property @{
            "SessionName" = $result.trim().substring(0, $result.trim().indexof(" ")).trim(">");
            "Username" = $result.Substring($starters.Username, $result.IndexOf(" ", $starters.Username) - $starters.Username);
            "ID" = $result.Substring($result.IndexOf(" ", $starters.Username), $starters.ID - $result.IndexOf(" ", $starters.Username) + 2).trim();
            "State" = $result.Substring($starters.State, $result.IndexOf(" ", $starters.State)-$starters.State).trim();
            "Type" = $result.Substring($starters.Type, $starters.Device - $starters.Type).trim();
            "Device" = $result.Substring($starters.Device).trim()
         }
      } 
      catch 
      {
         $e = $_;
         Write-Log "ERROR: on $srv" + $e.PSMessageDetails
      }
   }
}

If(!($richTextBox1.lines ))
{
$statusBar1.Text="Enter Server name.."
}
else
{
$servers = $richTextBox1.lines
foreach($srv in $servers)
{ 
$sessions += "`n" 
$sessions += "*************"
$sessions += $srv
$sessions += "************* `n"
if(!(test-connection $srv -count 2))
{
Write-Log "ERROR: Server $srv is NOT reachable"
Write-host "ERROR: Server $srv is NOT reachable"
$statusBar1.Text="ERROR: Server $srv is NOT reachable"
$sessions += "$srv is Not Reachable `n"
}
elseif(test-connection $srv -count 2)
{

$getSessions = Get-Sessions | ? {$_.UserName -ne ""} | Select ID, UserName
foreach ($session in $getSessions)
{
 $sessions += $session.Username
 $sessions += "`n" 
}
write-host $sessions
}
}
$richTextBox2.lines = $sessions
$sessions=""
$statusBar1.Text="Done"
Write-Host "=========================================="
Write-host "Collected sessions from ALL SERVERS"
Write-Host "=========================================="
}
}

$handler_form1_Load= 
{
#TODO: Place custom script here
$statusBar1.Text="Enter server names in text box ( one server per line)"
}

$button4_OnClick= 
{
$form1.Close()

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 502
$System_Drawing_Size.Width = 600
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Arun - Disconnect session"
$form1.add_Load($handler_form1_Load)


#new code

$button9.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 45
$System_Drawing_Point.Y = 450
$button9.Location = $System_Drawing_Point
$button9.Name = "button9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 115
$button9.Size = $System_Drawing_Size
$button9.TabIndex = 12
$button9.Text = "Logoff Selected"
$button9.UseVisualStyleBackColor = $True
$button9.add_Click($button9_OnClick)

$form1.Controls.Add($button9)


$button8.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 312
$System_Drawing_Point.Y = 343
$button8.Location = $System_Drawing_Point
$button8.Name = "button8"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 98
$button8.Size = $System_Drawing_Size
$button8.TabIndex = 11
$button8.Text = "Get Sessions"
$button8.UseVisualStyleBackColor = $True
$button8.add_Click($button8_OnClick)
$form1.Controls.Add($button8)


$label9.DataBindings.DefaultDataSourceUpdateMode = 0
$label9.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 346
$label9.Location = $System_Drawing_Point
$label9.Name = "label9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 88
$label9.Size = $System_Drawing_Size
$label9.TabIndex = 10
$label9.Text = "Server Name"
$label9.TextAlign = 16

$form1.Controls.Add($label9)

$textBox9.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 156
$System_Drawing_Point.Y = 346
$textBox9.Location = $System_Drawing_Point
$textBox9.Name = "textBox9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 121
$textBox9.Size = $System_Drawing_Size
$textBox9.TabIndex = 9

$form1.Controls.Add($textBox9)


$checkBox8.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 410
$System_Drawing_Point.Y = 415
$checkBox8.Location = $System_Drawing_Point
$checkBox8.Name = "checkBox8"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox8.Size = $System_Drawing_Size
$checkBox8.TabIndex = 8
$checkBox8.Text = ""
$checkBox8.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox8)

$label17.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 440
$System_Drawing_Point.Y = 415
$label17.Location = $System_Drawing_Point
$label17.Name = "label17"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label17.Size = $System_Drawing_Size
$label17.TabIndex = 0
$label17.Text = ""
$label17.TextAlign = 16
$label17.add_Click($handler_label1_Click)
$form1.Controls.Add($label17)

$checkBox7.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 410
$System_Drawing_Point.Y = 384
$checkBox7.Location = $System_Drawing_Point
$checkBox7.Name = "checkBox7"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox7.Size = $System_Drawing_Size
$checkBox7.TabIndex = 7
$checkBox7.Text = ""
$checkBox7.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox7)

$label16.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 440
$System_Drawing_Point.Y = 384
$label16.Location = $System_Drawing_Point
$label16.Name = "label16"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label16.Size = $System_Drawing_Size
$label16.TabIndex = 0
$label16.Text = ""
$label16.TextAlign = 16
$label16.add_Click($handler_label1_Click)
$form1.Controls.Add($label16)

$checkBox6.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 299
$System_Drawing_Point.Y = 414
$checkBox6.Location = $System_Drawing_Point
$checkBox6.Name = "checkBox6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox6.Size = $System_Drawing_Size
$checkBox6.TabIndex = 6
$checkBox6.Text = ""
$checkBox6.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox6)

$label15.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 329
$System_Drawing_Point.Y = 414
$label15.Location = $System_Drawing_Point
$label15.Name = "label15"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label15.Size = $System_Drawing_Size
$label15.TabIndex = 0
$label15.Text = ""
$label15.TextAlign = 16
$label15.add_Click($handler_label1_Click)
$form1.Controls.Add($label15)

$checkBox5.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 299
$System_Drawing_Point.Y = 384
$checkBox5.Location = $System_Drawing_Point
$checkBox5.Name = "checkBox5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox5.Size = $System_Drawing_Size
$checkBox5.TabIndex = 5
$checkBox5.Text = ""
$checkBox5.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox5)

$label14.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 330
$System_Drawing_Point.Y = 384
$label14.Location = $System_Drawing_Point
$label14.Name = "label14"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label14.Size = $System_Drawing_Size
$label14.TabIndex = 0
$label14.Text = ""
$label14.TextAlign = 16
$label14.add_Click($handler_label1_Click)
$form1.Controls.Add($label14)

$checkBox4.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 414
$checkBox4.Location = $System_Drawing_Point
$checkBox4.Name = "checkBox4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox4.Size = $System_Drawing_Size
$checkBox4.TabIndex = 4
$checkBox4.Text = ""
$checkBox4.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox4)

$label13.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 203
$System_Drawing_Point.Y = 414
$label13.Location = $System_Drawing_Point
$label13.Name = "label13"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label13.Size = $System_Drawing_Size
$label13.TabIndex = 0
$label13.Text = ""
$label13.TextAlign = 16
$label13.add_Click($handler_label1_Click)
$form1.Controls.Add($label13)

$checkBox3.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 384
$checkBox3.Location = $System_Drawing_Point
$checkBox3.Name = "checkBox3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox3.Size = $System_Drawing_Size
$checkBox3.TabIndex = 3
$checkBox3.Text = ""
$checkBox3.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox3)

$label12.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 203
$System_Drawing_Point.Y = 384
$label12.Location = $System_Drawing_Point
$label12.Name = "label12"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label12.Size = $System_Drawing_Size
$label12.TabIndex = 0
$label12.Text = ""
$label12.TextAlign = 16
$label12.add_Click($handler_label1_Click)
$form1.Controls.Add($label12)


$checkBox2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 414
$checkBox2.Location = $System_Drawing_Point
$checkBox2.Name = "checkBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox2.Size = $System_Drawing_Size
$checkBox2.TabIndex = 2
$checkBox2.Text = ""
$checkBox2.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox2)

$label11.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 90
$System_Drawing_Point.Y = 414
$label11.Location = $System_Drawing_Point
$label11.Name = "label11"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label11.Size = $System_Drawing_Size
$label11.TabIndex = 0
$label11.Text = ""
$label11.TextAlign = 16
$label11.add_Click($handler_label1_Click)
$form1.Controls.Add($label11)


$checkBox1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 384
$checkBox1.Location = $System_Drawing_Point
$checkBox1.Name = "checkBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 20
$checkBox1.Size = $System_Drawing_Size
$checkBox1.TabIndex = 1
$checkBox1.Text = ""
$checkBox1.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox1)


$label10.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 90
$System_Drawing_Point.Y = 384
$label10.Location = $System_Drawing_Point
$label10.Name = "label10"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 80
$label10.Size = $System_Drawing_Size
$label10.TabIndex = 0
$label10.Text = ""
$label10.TextAlign = 16
$label10.add_Click($handler_label1_Click)

$form1.Controls.Add($label10)


$label8.DataBindings.DefaultDataSourceUpdateMode = 0
$label8.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 307
$label8.Location = $System_Drawing_Point
$label8.Name = "label8"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 204
$label8.Size = $System_Drawing_Size
$label8.TabIndex = 0
$label8.Text = "Logoff selected sessions:"
$label8.TextAlign = 16
$label8.add_Click($handler_label1_Click)

$form1.Controls.Add($label8)

#end of new code 



$label2.DataBindings.DefaultDataSourceUpdateMode = 0
$label2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 296
$System_Drawing_Point.Y = 31
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 8
$label2.Text = "Sessions"
$label2.TextAlign = 32

$form1.Controls.Add($label2)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0
$label1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 79
$System_Drawing_Point.Y = 32
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 7
$label1.Text = "Servers"
$label1.TextAlign = 32

$form1.Controls.Add($label1)


$button4.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 384
$System_Drawing_Point.Y = 450
$button4.Location = $System_Drawing_Point
$button4.Name = "button4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button4.Size = $System_Drawing_Size
$button4.TabIndex = 6
$button4.Text = "Exit"
$button4.UseVisualStyleBackColor = $True
$button4.add_Click($button4_OnClick)

$form1.Controls.Add($button4)

$richTextBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 57
$System_Drawing_Point.Y = 67
$richTextBox1.Location = $System_Drawing_Point
$richTextBox1.Name = "richTextBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 169
$System_Drawing_Size.Width = 154
$richTextBox1.Size = $System_Drawing_Size
$richTextBox1.TabIndex = 5
$richTextBox1.Text = ""

$form1.Controls.Add($richTextBox1)

$statusBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 299
$statusBar1.Location = $System_Drawing_Point
$statusBar1.Name = "statusBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 503
$statusBar1.Size = $System_Drawing_Size
$statusBar1.TabIndex = 4
$statusBar1.Text = ""

$form1.Controls.Add($statusBar1)


$button3.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 268
$System_Drawing_Point.Y = 261
$button3.Location = $System_Drawing_Point
$button3.Name = "button3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button3.Size = $System_Drawing_Size
$button3.TabIndex = 3
$button3.Text = "Clear"
$button3.UseVisualStyleBackColor = $True
$button3.add_Click($button3_OnClick)

$form1.Controls.Add($button3)


$button11.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 268
$System_Drawing_Point.Y = 450
$button11.Location = $System_Drawing_Point
$button11.Name = "button11"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button11.Size = $System_Drawing_Size
$button11.TabIndex = 3
$button11.Text = "Clear"
$button11.UseVisualStyleBackColor = $True
$button11.add_Click($button11_OnClick)
$form1.Controls.Add($button11)

$button2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 154
$System_Drawing_Point.Y = 261
$button2.Location = $System_Drawing_Point
$button2.Name = "button2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button2.Size = $System_Drawing_Size
$button2.TabIndex = 2
$button2.Text = "Get Sessions"
$button2.UseVisualStyleBackColor = $True
$button2.add_Click($button2_OnClick)

$form1.Controls.Add($button2)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 45
$System_Drawing_Point.Y = 261
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 1
$button1.Text = "Logoff All"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($button1_OnClick)

$form1.Controls.Add($button1)




$richTextBox2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 285
$System_Drawing_Point.Y = 67
$richTextBox2.Location = $System_Drawing_Point
$richTextBox2.Name = "richTextBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 169
$System_Drawing_Size.Width = 157
$richTextBox2.Size = $System_Drawing_Size
$richTextBox2.TabIndex = 5
$richTextBox2.Text = ""

$form1.Controls.Add($richTextBox2)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
