name: ScriptingItOps
on:
  push:
    branches:
      - "main" 

  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  # build the image 
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use docker login to log into ACR 
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
        # comment out the login-server parameter if using docker hub
          login-server: 'ACRt11.azurecr.io'
          username: 'Mpcaz123'
          password: '4Nq7fNckGPkQOjS3jexiMMI1Az0a24dBwTZuf+wHNu+ACRBACFr7'

      # Build and push your image to Azure Container Registry 
      - name: Build and Push container to ACR
        run: |
          dir
          docker images
          docker build --file= D:\a\Arun\Arun\Docker-Test\Dockerfile -t testwin/wintest123:${{ github.sha }} .
          docker images
          docker push testwin/wintest123:${{ github.sha }}  
