name: yt kids Workflow

on:
  schedule:
    - cron: '31 */3 * * *'  # Runs every 4 hours
  #push:
  #  branches:
  #    - main  # Adjust the branch name as needed
  #pull_request:
  #  branches:
  #    - main  # Adjust the branch name as needed
  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
    
    - name: Install ImageMagick
      run: sudo apt-get update &&  sudo apt-get install -y --install-suggests imagemagick

    #- name: Install ImageMagick2
    ## ImageMagicK Installation 
    #  run: mkdir -p /tmp/distr && cd /tmp/distr && wget https://download.imagemagick.org/archive/releases/ImageMagick-7.1.1-25.tar.xz && tar xvf ImageMagick-7.1.1-25.tar.xz && cd ImageMagick-7.1.1-25 && ./configure --enable-shared=yes --disable-static --without-perl &&  make && sudo make install && sudo ldconfig /usr/local/lib
    - name: Install ImageMagick1
      run:  |
        #sudo apt-get install libmagick++-dev
        cat "/etc/ImageMagick-6/policy.xml"
        sudo cp -f .github/policy.xml /etc/ImageMagick-6/policy.xml
        cat "/etc/ImageMagick-6/policy.xml"
    #- name: update ImageMagick installation2
    #  run: sudo sed -i 's/domain=${DQT}path${DQT} rights=${DQT}none${DQT} pattern="@*"/domain="coder" rights="none" pattern="text"/g' /etc/ImageMagick-6/policy.xml
    #- name: Verify ImageMagick installation
    #  run: convert --version
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install moviepy
        python -m pip install gtts
        #python -m pip install mutagen
        python -m pip install google
        python -m pip install google_auth_oauthlib
        python -m pip install google-api-python-client
        python -m pip install facebook-sdk 
        python -m pip install matplotlib
        python -m pip install openai
        python -m pip install Pillow

